name: Build & Deploy Spring Security

on:
  push:
    branches:
      - master
      - dev

jobs:
  build-deploy:
    name: Build and Deploy Spring Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean 
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-security:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/SpringSecurity:latest